import { NextPage } from 'next';
import Head from 'next/head';

const ServiceComponent: NextPage = () => {
  return (
    <div className={'container'}>
      <Head>
        <title>Services | UDS Systems</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={'main'}>
        <h1>servicePage page</h1>
      </main>
    </div>
  );
};

export default ServiceComponent;
