import {NextPage} from "next";
import Head from "next/head";

const PrivacyPolicyComponent: NextPage = () => {
    return (
        <div className={"container"}>
            <Head>
                <title>Privacy Policy | UDS Systems</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={"main"}>
                <h1 className={"title"}>
                    YOUR PRIVACY IS CRITICALLY IMPORTANT TO US
                </h1>
            </main>
        </div>
    );
};

export default PrivacyPolicyComponent;
