import {NextPage} from "next";
import Head from "next/head";
import Accordion from "../../components/sharedComponents/Accordion";

const PrivacyPolicyComponent: NextPage = () => {

    const privacyItems = [
        {
            title: "UDS Systems may be contacted as follows:",
            content: "This Privacy Policy, together with the Terms and conditions posted on our Website, set forth the general rules and policies governing your use of our Website. When purchasing additional services, you may be required to agree to additional terms and conditions."
        },
        {
            title: "Lawful collection and processing",
            content: "You are not required to provide us your personal data, but without adequate information we will not be able to provide you with some of our services."
        },
        {
            title: "Objectives of processing personal data",
            content: "We render products or services relating to easing operation of and access to third party services, including but not limited to Microsoft Dynamics 365, PowerApps and Azure. We require your personal data in order to render services to:"
        },
        {
            title: "Processed personal data",
            content: "We render products or services relating to easing operation of and access to third party services, including but not limited to Microsoft Dynamics 365, PowerApps and Azure. We require your personal data in order to render services to:"
        }
    ]

    return (
        <div>
            <Head>
                <title>Privacy Policy | UDS Systems</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={"main privacy"}>
                <div className={"firstScreen"}>
                    <div className={"content container"}>
                        <h1 className={"title"}>
                            Welcome to our Privacy Policy
                        </h1>
                        <p className={"subtitle"}>
                            Your privacy is critically important for us
                        </p>
                    </div>
                </div>
                <div className={"content container"}>
                    <Accordion items={privacyItems}/>
                </div>
            </main>
        </div>
    );
};

export default PrivacyPolicyComponent;
