import type { NextPage } from 'next';
import Head from 'next/head';

const RootComponent: NextPage = () => {
  return (
    <div className={"container"}>
      <Head>
        <title>Home | UDS Systems</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"main"}>
        <h1 className={"title"}>
         home page
        </h1>
      </main>
    </div>
  );
};

export default RootComponent;
